### ISSUE TITLE
Add plugin checking for circular dependencies in webpack

### ISSUE THREAD

**Issue by tomhelmer** [adaptdk/react_boilerplate#14]
Detect modules with circular dependencies when bundling with webpack.

Circular dependencies are often a necessity in complex software, the presence of a circular dependency doesn't always imply a bug, but in the case where you believe a bug exists, this module may help find it.

https://www.npmjs.com/package/circular-dependency-plugin

**Comment by mthines** [comment]
Solved in PR
https://github.com/adaptdk/react_boilerplate/pull/22
