### ISSUE TITLE
Add lint pre-commit hook

### ISSUE THREAD

**Issue by tomhelmer** [adaptdk/react_boilerplate#15]
Add devdependency:
https://www.npmjs.com/package/pre-commit

In package.json:

```
"pre-commit": [
    "lint"
  ],
```

.. and add a 'lint' entry under 'scripts'

**Comment by mthines** [comment]
We've already been looking into pre-commit hooks, so I'm a big fan of this idea!

**Comment by mthines** [comment]
This has now been solves with [`husky`](https://www.npmjs.com/package/husky) and eslint / typescript/eslint
